export const ROUTES = {
  root: "/",
  about: "/about",
  stub: "/stub",
  slidermain: "/slider",
  contacts: "/contacts",
  payment: "/payment",
  brends: "/brends",
  anckers: "/anckers",
  bolts: "/bolts",
  nuts: "/nuts",
  vints: "/vints",
  burs: "/burs",
  gaechs: "/gaechs",
  otvertki: "/otvertki",
  sverls: "/sverls",
};
